name: CD

on:
  push:
    branches:
      - main
      - master
      - test/api-gw # Test trigger for specific branch
      - test/private-cors # Test trigger for specific branch
    # Trigger on version tags for production deployments
    tags:
      - 'v*.*.*'  # Matches tags like v1.0.0, v2.1.3, etc.

permissions:
  id-token: write
  contents: read

env:
  # Set environment based on whether the ref is a tag or a branch
  # If it's a tag starting with 'v', use 'production', else 'development'
  DEPLOYMENT_ENVIRONMENT: ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'development' }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_DEPLOYMENT_ROLE: ${{ vars.AWS_DEPLOYMENT_ROLE_NAME }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ZONE_ID: ${{ vars.CLOUDFLARE_ZONE_ID }}
  TERRAFORM_BACKEND_BUCKET: ${{ vars.TERRAFORM_BACKEND_BUCKET }}

jobs:
  cd:
    # Set environment based on whether the ref is a tag or a branch
    # If it's a tag starting with 'v', use 'production', else 'development'
    environment:  ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'development' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v5

    - name: Setup Terraform Environment Variables
      run: |
        echo "TF_VAR_environment=${{ env.DEPLOYMENT_ENVIRONMENT }}" >> $GITHUB_ENV
        echo "TF_VAR_zone_id=${{ vars.CLOUDFLARE_ZONE_ID }}" >> $GITHUB_ENV

    - name: Display Execution Context
      run: |
        echo "::group::Execution Context"
        echo "Environment: ${{ env.DEPLOYMENT_ENVIRONMENT }}"
        echo "AWS Region: ${{ env.AWS_REGION }}"
        echo "AWS ACCOUNT ID: ${{ env.AWS_ACCOUNT_ID }}"
        echo "AWS Deployment Role: ${{ env.AWS_DEPLOYMENT_ROLE }}"
        echo "Cloudflare API Token: ${{ secrets.CLOUDFLARE_API_TOKEN }}"
        echo "Cloudflare Zone ID: ${{ vars.CLOUDFLARE_ZONE_ID }}"
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub Event: ${{ github.event_name }}"
        echo "Terraform version: $(terraform --version)"
        echo "Terraform Backend Bucket: ${{ env.TERRAFORM_BACKEND_BUCKET }}"
        echo "TF_VAR_environment: $TF_VAR_environment"
        echo "TF_VAR_zone_id: $TF_VAR_zone_id"
        echo "::endgroup::"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_DEPLOYMENT_ROLE }}
        role-session-name: DeploymentSession

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.4

    - name: Terraform Init (AWS)
      run: |
        terraform init --input=false \
          -backend-config="bucket=${{ env.TERRAFORM_BACKEND_BUCKET }}" \
          -backend-config="region=${{ env.AWS_REGION }}"
      working-directory: ./aws

    # - name: Terraform Init (Cloudflare)
    #   run: |
    #     terraform init --input=false \
    #       -backend-config="bucket=${{ env.TERRAFORM_BACKEND_BUCKET }}" \
    #       -backend-config="region=${{ env.AWS_REGION }}"
    #   working-directory: ./cloudflare

    - name: Terraform Apply (AWS)
      run: terraform apply -auto-approve
      working-directory: ./aws

    # - name: Terraform Apply (Cloudflare)
    #   run: terraform apply -auto-approve
    #   working-directory: ./cloudflare
