name: CI

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - ci/add-ci-checks

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rust: [stable]

    steps:

    - uses: actions/checkout@v5
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Display Execution Context
      run: |
        echo "::group::Execution Context"
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub Event: ${{ github.event_name }}"
        echo "Terraform version: $(terraform --version)"
    - name: Code Formatting Check
      run: terraform fmt --check --recursive
