name: CI

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - ci/add-ci-checks

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rust: [stable]

    steps:
    - uses: actions/checkout@v5
    - name: Code Formatting Check
      run: terraform fmt --check --recursive
